name: Weave-policy-validator
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: weaveworks/weave-action@v1
        with:
          path: deploy
          policies-path: policies
          remediate: true # enable auto remediation
          sarif-file: results.sarif ## export result in SARF format to send it to github code scanning

      # send results to github code scanning
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: results.sari
